# Generated by Django 6.0.5 on 2026-05-31 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('1', 'ورزشی'), ('2', 'شبکه اجتماعی')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
