# Generated by Django 6.0.5 on 2026-06-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='محتوا'),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_add',
            field=models.DateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(choices=[('1', 'ورزشی'), ('2', 'شبکه اجتماعی')], max_length=1, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=60, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(choices=[('iran', 'ایران'), ('usa', 'امریکا')], default='iran', max_length=20, verbose_name='کشور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passord',
            field=models.CharField(max_length=32, verbose_name='گذرواژه'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_picutres', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=60, verbose_name='نام کاربری'),
        ),
    ]
